export class Hero {
    name: string = '';
    awakeningLevel: string = '';
    necklaceStat: string = '';
    ringStat: string = '';
    bootStat: string = '';
    attack: string = '';
    defense: string = '';
    health: string = '';
    speed: string = '';
    critChance: string = '';
    critDamage: string = '';
    effectiveness: string = '';
    effectResistance: string = '';
    dualAttackChance: string = '';
    artifact: string = '';
    artifactLevel: string = '';
    imprintType: string = '';
    imprintLevel: string = '';
    setEffectOne: string = '';
    setEffectTwo: string = '';
    setEffectThree: string = '';
}